# Generated by Django 5.0.6 on 2024-05-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="post_images"
            ),
        ),
    ]
